### ISSUE TITLE
Linter complains about dead links due to non-existent releases

### ISSUE THREAD

**Issue by boris-martin** [precice/fenicsx-adapter#12]
The Markdown Linter flow fails because of links to non-existent things such as https://pypi.org/project/fenicsxprecice/#history
Should we release at some point to make it existent, update the doc to remove dead links, or simply ignore the issue until the adapter is ready ?

**Comment by IshaanDesai** [comment]
We do want to release in the near future, but till then we can remove or temporarily comment out such links so that the markdown linter workflow passes. I understand that is annoying to have a failing workflow when one is trying to merge PRs.
