### ISSUE TITLE
Develop existing FEniCS tutorials here

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenicsx-adapter#2]
To make development easier we develop the FEniCS-X tutorials here. As soon as this adapter is stable, we will migrate the tutorials to https://github.com/precice/tutorials. Our goal is to port all FEniCS tutorials to FEniCS-X. This is the complete list:

* [`partitioned-heat-conduction`](https://github.com/precice/tutorials/tree/master/partitioned-heat-conduction): As a test for simple geometries and scalar valued coupling data
* [`partitioned-heat-conduction-complex`](https://github.com/precice/tutorials/tree/master/partitioned-heat-conduction-complex): As a test for complex geometries and vector valued coupling data.
* [`volume-coupled-diffusion`](https://github.com/precice/tutorials/tree/master/volume-coupled-diffusion): As a test case for volume coupling
* [`perpendicular-flap`](https://github.com/precice/tutorials/tree/master/perpendicular-flap): For FSI
* [`flow-over-heated`](https://github.com/precice/tutorials/tree/master/flow-over-heated-plate): For CHT

We should follow the folder structure and naming of the `tutorials` repository and put everything into the folder `fenicsx-adapter/tutorials`. The second participant (openfoam, su2...) and the preCICE configuration file should not be pushed into this repository, but just manually copied from the tutorials.

**Comment by BenjaminRodenberg** [comment]
#15 and https://github.com/precice/tutorials/pull/317 represent a stable case for a limited set of features. We therefore decided to properly integrate the tutorial in the tutorials repository.

**Comment by IshaanDesai** [comment]
Now that we have ported the `partitioned-heat-conduction` tutorial from this repo into the tutorials, do we still want to pursue the strategy of developing tutorials here and porting them later?

**Comment by BenjaminRodenberg** [comment]
From my current perspective: No. I think the API is sufficiently stable that we should be able to develop the remaining tutorials directly in the tutorials repository. If we find out that we run into problems, we can just reopen this issue. We can still create an issue in the tutorials repo to keep track of the tutorials that still need to be ported. This is also a nice overview, if somebody wants to do a thesis or HiWi project on porting one of the tutorials.

**Comment by IshaanDesai** [comment]
Agreeing with @BenjaminRodenberg and hence closing this issue.
