### ISSUE TITLE
preCICE version in tutorials

### ISSUE THREAD

**Issue by shrunkjungle** [precice/fenicsx-adapter#27]
Hi, I was wondering whether it would be possible to add the version of preCICE that was used in the FEniCSx partitioned heat tutorial given [here](https://github.com/precice/fenicsx-adapter/tree/dev-partitioned-heat-equation/tutorials/partitioned-heat-conduction).

I am trying to reproduce results from the tutorial but run into many attribute errors from within preCICE, which I assume are form syntax changes over the years.

**Comment by uekerman** [comment]
It should be preCICE v2. I recommend using the newest v2: [v2.5.1](https://github.com/precice/precice/releases/tag/v2.5.1).
