### ISSUE TITLE
Use proper release of FEniCS-X for development

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenicsx-adapter#3]
Currently we are using https://github.com/FEniCS/dolfinx/commit/358470227bf9b7dea179fca52fbd36182a277010 for development of this adapter. Our goal is to use a (stable) release in the future. We are not using the latest release https://github.com/FEniCS/dolfinx/releases/tag/v0.3.0, because some functionality that we need is missing/not working. See https://fenicsproject.discourse.group/t/copying-a-function-in-dolfinx/7425/2.

**Comment by arvedes** [comment]
Let's go for v0.4.0, it has just been released!
https://github.com/FEniCS/dolfinx/releases/tag/v0.4.0

**Comment by arvedes** [comment]
I updated #1 to dolfinx v0.4.1.
