### ISSUE TITLE
Provide Dockerfile as basis for testing in this repository

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/fenicsx-adapter#6]
Related to #3. Currently we are using a specific development version of FEniCS-X for our development. We should add a Dockerfile to this repository which is used as a basis for testing. A good template is provided here: https://github.com/nemocrys/dolfinx-openfoam/blob/main/docker/Dockerfile.

We need the follwoing:

* FEniCS-X (we now have to build manually, ~~but should be replaced with `dolfinx/dolfinx:latest` in the future.~~ but should be replaced with installation of a binary in the future; see [the dockerfile for the fenics-adapter](https://github.com/precice/fenics-adapter/blob/develop/tools/releasing/packaging/docker/Dockerfile))
* preCICE (use preCICE 2.3.0)
* python-bindings (use 2.3.0.1)

We don't need/want:

* OpenFOAM and other dependencies.

**Comment by arvedes** [comment]
I added a Dockerfile based on the configuration above. It is not perfect at all and a way too extensive, but I think it should work for now.

**Comment by arvedes** [comment]
For now the Dockerfile is okay, but we should update / replace it once there is a new release. Refer to the discussion here: https://github.com/precice/fenicsx-adapter/pull/1#discussion_r819018128

**Comment by BenjaminRodenberg** [comment]
Then let's keep this issue open until we have a dockerfile that meets all requirements. 

* Current state: Dockerfile builds fenics-x and preCICE from source.
* Additional requirement: Use a base-image from https://hub.docker.com/u/precice or https://hub.docker.com/u/fenicsproject to avoid duplication of installation commands. I prefer using the preCICE image as a basis, because this is consistent with our current architecture for the systemtests (see also https://github.com/precice/openfoam-adapter/pull/184).
